//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Unidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesUnidades : DbContext
    {
        public EntitiesUnidades()
            : base("name=EntitiesUnidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UnidadAngle> UnidadAngle { get; set; }
        public virtual DbSet<UnidadCantidad> UnidadCantidad { get; set; }
        public virtual DbSet<UnidadDistancia> UnidadDistancia { get; set; }
        public virtual DbSet<UnidadForce> UnidadForce { get; set; }
        public virtual DbSet<UnidadMass> UnidadMass { get; set; }
        public virtual DbSet<UnidadPresion> UnidadPresion { get; set; }
        public virtual DbSet<UnidadTiempo> UnidadTiempo { get; set; }
        public virtual DbSet<UnidadDureza> UnidadDureza { get; set; }
    }
}
