//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Unidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadAngle
    {
        public int ID_UNIDAD_ANGLE { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> ValorGrados { get; set; }
    }
}
