//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_MOTIVO_CAMBIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_MOTIVO_CAMBIO()
        {
            this.TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO = new HashSet<TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO>();
        }
    
        public int ID_MOTIVO_CAMBIO { get; set; }
        public string MOTIVO_CAMBIO { get; set; }
        public string DESCRIPCION_CAMBIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO> TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO { get; set; }
    }
}
