//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentroTrabajo()
        {
            this.TR_LECCIONES_CENTROSTRABAJO = new HashSet<TR_LECCIONES_CENTROSTRABAJO>();
        }
    
        public string CentroTrabajo1 { get; set; }
        public Nullable<double> TiempoSetup { get; set; }
        public string NombreOperacion { get; set; }
        public string ObjetoXML { get; set; }
        public string ObjetoXMLVista { get; set; }
        public string NombreIngles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_LECCIONES_CENTROSTRABAJO> TR_LECCIONES_CENTROSTRABAJO { get; set; }
    }
}
