//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesUsuario : DbContext
    {
        public EntitiesUsuario()
            : base("name=EntitiesUsuario")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<PrivilegioUsuario> PrivilegioUsuario { get; set; }
        public virtual DbSet<TBL_ARCHIVO_LECCIONES> TBL_ARCHIVO_LECCIONES { get; set; }
        public virtual DbSet<CentroTrabajo> CentroTrabajo { get; set; }
        public virtual DbSet<TBL_TIPOCAMBIO> TBL_TIPOCAMBIO { get; set; }
        public virtual DbSet<TR_LECCIONES_TIPOCAMBIO> TR_LECCIONES_TIPOCAMBIO { get; set; }
        public virtual DbSet<TR_LECCIONES_CENTROSTRABAJO> TR_LECCIONES_CENTROSTRABAJO { get; set; }
        public virtual DbSet<TBL_LECCIONES_APRENDIDAS> TBL_LECCIONES_APRENDIDAS { get; set; }
        public virtual DbSet<TBL_BITACORA_INGRESO> TBL_BITACORA_INGRESO { get; set; }
        public virtual DbSet<TBL_USERS_DETAILS> TBL_USERS_DETAILS { get; set; }
        public virtual DbSet<CAT_MOTIVO_CAMBIO> CAT_MOTIVO_CAMBIO { get; set; }
        public virtual DbSet<TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO> TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO { get; set; }
        public virtual DbSet<TBL_SOLICITUD_CORREO> TBL_SOLICITUD_CORREO { get; set; }
    }
}
