//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilUsuario
    {
        public int ID_PERFIL_USUARIO { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<bool> RGP { get; set; }
        public Nullable<bool> TOOLING { get; set; }
        public Nullable<bool> RAW_MATERIAL { get; set; }
        public Nullable<bool> STANDAR_TIME { get; set; }
        public Nullable<bool> QUOTES { get; set; }
        public Nullable<bool> CIT { get; set; }
        public Nullable<bool> DATA { get; set; }
        public Nullable<bool> USER_PROFILE { get; set; }
        public Nullable<bool> HELP { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
