//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARCHIVO_LECCIONES
    {
        public int ID_ARCHIVO_LECCIONES { get; set; }
        public int ID_LECCIONES_APRENDIDAS { get; set; }
        public byte[] ARCHIVO { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public string EXT { get; set; }
    
        public virtual TBL_LECCIONES_APRENDIDAS TBL_LECCIONES_APRENDIDAS { get; set; }
    }
}
