//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIPOCAMBIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TIPOCAMBIO()
        {
            this.TR_LECCIONES_TIPOCAMBIO = new HashSet<TR_LECCIONES_TIPOCAMBIO>();
        }
    
        public int ID_TIPOCAMBIO { get; set; }
        public string NOMBRETIPOCAMBIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_LECCIONES_TIPOCAMBIO> TR_LECCIONES_TIPOCAMBIO { get; set; }
    }
}
