//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERS_DETAILS
    {
        public int ID_USERS_DETAILS { get; set; }
        public string ID_USUARIO { get; set; }
        public string URL_PHOTO { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
