//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SOLICITUD_CORREO
    {
        public int ID_SOLICITUD_CORREO { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public string TITLE { get; set; }
        public string BODY { get; set; }
        public string RECIPIENTS { get; set; }
        public Nullable<bool> BAN_EJECUTADA { get; set; }
        public Nullable<System.DateTime> FECHA_EJECUTADA { get; set; }
        public string ORIGEN { get; set; }
        public Nullable<int> ID_ARCHIVO { get; set; }
    }
}
