//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERS_DETAILS
    {
        public int ID_USERS_DETAILS { get; set; }
        public string ID_USUARIO { get; set; }
        public string URL_PHOTO { get; set; }
        public Nullable<bool> IS_AVAILABLE_EMAIL { get; set; }
        public Nullable<bool> TEMPORAL_PASSWORD { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
