//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LECCIONES_APRENDIDAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LECCIONES_APRENDIDAS()
        {
            this.TBL_ARCHIVO_LECCIONES = new HashSet<TBL_ARCHIVO_LECCIONES>();
            this.TR_LECCIONES_TIPOCAMBIO = new HashSet<TR_LECCIONES_TIPOCAMBIO>();
            this.TR_LECCIONES_CENTROSTRABAJO = new HashSet<TR_LECCIONES_CENTROSTRABAJO>();
            this.TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO = new HashSet<TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO>();
        }
    
        public int ID_LECCIONES_APRENDIDAS { get; set; }
        public string ID_USUARIO { get; set; }
        public string COMPONENTE { get; set; }
        public string DESCRIPCION_PROBLEMA { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public string REPORTADO_POR { get; set; }
        public string SOLICITUD_DE_TRABAJO_INGENIERIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ARCHIVO_LECCIONES> TBL_ARCHIVO_LECCIONES { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_LECCIONES_TIPOCAMBIO> TR_LECCIONES_TIPOCAMBIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_LECCIONES_CENTROSTRABAJO> TR_LECCIONES_CENTROSTRABAJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO> TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO { get; set; }
    }
}
