//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BITACORA_INGRESO
    {
        public int ID_BITACORA_INGRESOS { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string NOMBRE_COMPUTADORA { get; set; }
    }
}
