//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARCHIVO_LECCIONES
    {
        public int ID_ARCHIVO_LECCIONES { get; set; }
        public int ID_LECCIONES_APRENDIDAS { get; set; }
        public byte[] ARCHIVO { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public string EXT { get; set; }
    
        public virtual TBL_LECCIONES_APRENDIDAS TBL_LECCIONES_APRENDIDAS { get; set; }
    }
}
