//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LECCIONES_TIPOCAMBIO
    {
        public int ID_LECCIONES_TIPOCAMBIO { get; set; }
        public int ID_TIPOCAMBIO { get; set; }
        public int ID_LECCIONAPRENDIDA { get; set; }
    
        public virtual TBL_TIPOCAMBIO TBL_TIPOCAMBIO { get; set; }
        public virtual TBL_LECCIONES_APRENDIDAS TBL_LECCIONES_APRENDIDAS { get; set; }
    }
}
