//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO
    {
        public int ID_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO { get; set; }
        public Nullable<int> ID_LECCION_APRENDIDA { get; set; }
        public Nullable<int> ID_MOTIVO_CAMBIO { get; set; }
    
        public virtual CAT_MOTIVO_CAMBIO CAT_MOTIVO_CAMBIO { get; set; }
        public virtual TBL_LECCIONES_APRENDIDAS TBL_LECCIONES_APRENDIDAS { get; set; }
    }
}
