//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO
    {
        public int ID_LECCIONES_APRENDIDAS_MOTIVO_CAMBIO { get; set; }
        public Nullable<int> ID_LECCION_APRENDIDA { get; set; }
        public Nullable<int> ID_MOTIVO_CAMBIO { get; set; }
    
        public virtual CAT_MOTIVO_CAMBIO CAT_MOTIVO_CAMBIO { get; set; }
        public virtual TBL_LECCIONES_APRENDIDAS TBL_LECCIONES_APRENDIDAS { get; set; }
    }
}
