//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LECCIONES_CENTROSTRABAJO
    {
        public int ID_LECCIONES_CENTROTRABAJO { get; set; }
        public string ID_CENTROTRABAJO { get; set; }
        public int ID_LECCIONESAPRENDIDAS { get; set; }
    
        public virtual CentroTrabajo CentroTrabajo { get; set; }
        public virtual TBL_LECCIONES_APRENDIDAS TBL_LECCIONES_APRENDIDAS { get; set; }
    }
}
