//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string lblBtnLogin {
            get {
                return ResourceManager.GetString("lblBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the record?.
        /// </summary>
        public static string lblConfirmDeleteRecord {
            get {
                return ResourceManager.GetString("lblConfirmDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diameter.
        /// </summary>
        public static string lblDiameter {
            get {
                return ResourceManager.GetString("lblDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your credentials.
        /// </summary>
        public static string lblEnterCredentials {
            get {
                return ResourceManager.GetString("lblEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string lblInformation {
            get {
                return ResourceManager.GetString("lblInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in....
        /// </summary>
        public static string lblLogIn {
            get {
                return ResourceManager.GetString("lblLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your user/password are incorrects.
        /// </summary>
        public static string lblPasswordIncorrect {
            get {
                return ResourceManager.GetString("lblPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record deleted!.
        /// </summary>
        public static string lblRecordDeleted {
            get {
                return ResourceManager.GetString("lblRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thickness.
        /// </summary>
        public static string lblThickness {
            get {
                return ResourceManager.GetString("lblThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a password.
        /// </summary>
        public static string lblTxtContrasena {
            get {
                return ResourceManager.GetString("lblTxtContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a username.
        /// </summary>
        public static string lblTxtUserName {
            get {
                return ResourceManager.GetString("lblTxtUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user is not active.
        /// </summary>
        public static string lblUserNotActive {
            get {
                return ResourceManager.GetString("lblUserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width.
        /// </summary>
        public static string lblWidth {
            get {
                return ResourceManager.GetString("lblWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Working at operation: .
        /// </summary>
        public static string msgDoingOperation {
            get {
                return ResourceManager.GetString("msgDoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Woops, something went wrong.
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, fill all fields.
        /// </summary>
        public static string msgFillFlields {
            get {
                return ResourceManager.GetString("msgFillFlields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pattern was inserted with the code: .
        /// </summary>
        public static string msgPatternInserted {
            get {
                return ResourceManager.GetString("msgPatternInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The routing is ready.
        /// </summary>
        public static string msgRoutingReady {
            get {
                return ResourceManager.GetString("msgRoutingReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        public static string ttlAlerta {
            get {
                return ResourceManager.GetString("ttlAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication.
        /// </summary>
        public static string ttlAuthentication {
            get {
                return ResourceManager.GetString("ttlAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents Control.
        /// </summary>
        public static string ttlControlDocumentos {
            get {
                return ResourceManager.GetString("ttlControlDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        public static string ttlData {
            get {
                return ResourceManager.GetString("ttlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done.
        /// </summary>
        public static string ttlDone {
            get {
                return ResourceManager.GetString("ttlDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait a moment.
        /// </summary>
        public static string ttlEspereUnMomento {
            get {
                return ResourceManager.GetString("ttlEspereUnMomento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learned lessons.
        /// </summary>
        public static string ttlLessons {
            get {
                return ResourceManager.GetString("ttlLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quotes.
        /// </summary>
        public static string ttlQuotes {
            get {
                return ResourceManager.GetString("ttlQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw material.
        /// </summary>
        public static string ttlRawMaterial {
            get {
                return ResourceManager.GetString("ttlRawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Routing generation program.
        /// </summary>
        public static string ttlRouting {
            get {
                return ResourceManager.GetString("ttlRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click here to calculate a routing.
        /// </summary>
        public static string ttlRoutingAux {
            get {
                return ResourceManager.GetString("ttlRoutingAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standar time.
        /// </summary>
        public static string ttlStandarTime {
            get {
                return ResourceManager.GetString("ttlStandarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tooling.
        /// </summary>
        public static string ttlTooling {
            get {
                return ResourceManager.GetString("ttlTooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string ttlUser {
            get {
                return ResourceManager.GetString("ttlUser", resourceCulture);
            }
        }
    }
}
