//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Operaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arquetipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arquetipo()
        {
            this.TBL_CALCULO_ARQUETIPO = new HashSet<TBL_CALCULO_ARQUETIPO>();
            this.TBL_CALCULO_DETALLE = new HashSet<TBL_CALCULO_DETALLE>();
        }
    
        public string Codigo { get; set; }
        public string DescripcionGeneral { get; set; }
        public byte[] Imagen { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CALCULO_ARQUETIPO> TBL_CALCULO_ARQUETIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CALCULO_DETALLE> TBL_CALCULO_DETALLE { get; set; }
    }
}
