//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Operaciones
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityOperaciones : DbContext
    {
        public EntityOperaciones()
            : base("name=EntityOperaciones")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OperacionesRouter> OperacionesRouter { get; set; }
        public virtual DbSet<Arquetipo> Arquetipo { get; set; }
        public virtual DbSet<TBL_CALCULO_ARQUETIPO> TBL_CALCULO_ARQUETIPO { get; set; }
        public virtual DbSet<TBL_CALCULO_DETALLE> TBL_CALCULO_DETALLE { get; set; }
    }
}
