//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Operaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionesRouter
    {
        public int IdOperacion { get; set; }
        public string CentroTrabajo { get; set; }
        public string NombreIngles { get; set; }
        public string NombreEspañol { get; set; }
        public string IDObjectXML { get; set; }
    }
}
