//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class castings_widths
    {
        public string Codigo { get; set; }
        public Nullable<double> Nominal_Ring_Width_min { get; set; }
        public Nullable<double> Nominal_Ring_Width_max { get; set; }
        public Nullable<double> Minimum_casting_width { get; set; }
        public Nullable<double> ideal_casting_Width { get; set; }
        public string tipo { get; set; }
    }
}
