//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class castings_widths
    {
        public string Codigo { get; set; }
        public Nullable<double> Nominal_Ring_Width_min { get; set; }
        public Nullable<double> Nominal_Ring_Width_max { get; set; }
        public Nullable<double> Minimum_casting_width { get; set; }
        public Nullable<double> ideal_casting_Width { get; set; }
        public string tipo { get; set; }
    }
}
