//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_MATERIA_PRIMA_ACEROS
    {
        public string CODIGO { get; set; }
        public string ID_MATERIAL { get; set; }
        public Nullable<double> ESP_AXIAL { get; set; }
        public Nullable<double> ESP_RADIAL { get; set; }
        public string PROVEEDOR { get; set; }
        public string PROVEEDOR2 { get; set; }
    
        public virtual material material { get; set; }
    }
}
