//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_MATERIA_PRIMA_ACEROS
    {
        public string CODIGO { get; set; }
        public string ID_MATERIAL { get; set; }
        public Nullable<double> ESP_AXIAL { get; set; }
        public Nullable<double> ESP_RADIAL { get; set; }
        public string PROVEEDOR { get; set; }
        public string PROVEEDOR2 { get; set; }
    
        public virtual material material { get; set; }
    }
}
