//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_MATERIA_PRIMA_ROLADO
    {
        public string ID_MATERIA_PRIMA_ROLADO { get; set; }
        public string ID_ESPECIFICACION { get; set; }
        public string DESCRIPCION { get; set; }
        public string UM { get; set; }
        public double WIDTH { get; set; }
        public double GROOVE { get; set; }
        public double THICKNESS { get; set; }
        public string UBICACION { get; set; }
        public string ESPEC_PERFIL { get; set; }
    
        public virtual material material { get; set; }
    }
}
