//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compensacion_Piece
    {
        public int IdCompensacionPiece { get; set; }
        public string IdMaterial { get; set; }
        public Nullable<int> IdTipoAnillo { get; set; }
        public Nullable<double> Compensacion { get; set; }
    
        public virtual material material { get; set; }
        public virtual Tipo_Anillo Tipo_Anillo { get; set; }
    }
}
