//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriosSegmentos_
    {
        public int ID_CRITERIO_SEGMENTO { get; set; }
        public Nullable<double> MPAxialWidthMinPVD { get; set; }
        public Nullable<double> MPAxialWidthMaxPVD { get; set; }
        public Nullable<double> MPRadialThickMinPVD { get; set; }
        public Nullable<double> MPRadialThickMaxPVD { get; set; }
        public Nullable<double> MPAxialWidthMin { get; set; }
        public Nullable<double> MPAxialWidthMax { get; set; }
        public Nullable<double> MPRadialThickMin { get; set; }
        public Nullable<double> MPRadialThickMax { get; set; }
        public Nullable<double> MPRadialCromoMin { get; set; }
        public Nullable<double> MPRadialCromoMax { get; set; }
        public Nullable<double> DiscoMin { get; set; }
        public Nullable<double> DiscoMax { get; set; }
        public Nullable<double> CromoServicio { get; set; }
        public Nullable<double> CromoEO { get; set; }
        public Nullable<double> CromoFreeGapMin { get; set; }
        public Nullable<double> CromoFreeGapMax { get; set; }
        public Nullable<double> NitruFreeGapMin { get; set; }
        public Nullable<double> NitruFreeGapMax { get; set; }
        public Nullable<double> Nitru2FreeGapMin { get; set; }
        public Nullable<double> Nitru2FreeGapMax { get; set; }
        public Nullable<double> FreeGapSinCromoMin { get; set; }
        public Nullable<double> FreeGapSinCromoMax { get; set; }
        public Nullable<double> CenterWaferH1Min { get; set; }
        public Nullable<double> CenterWaferH1Max { get; set; }
        public Nullable<double> CromoCollarinMin { get; set; }
        public Nullable<double> CromoCollarinMax { get; set; }
        public Nullable<double> MangaNormMin { get; set; }
        public Nullable<double> MangaNormMax { get; set; }
        public Nullable<double> MangaNormAntesMin { get; set; }
        public Nullable<double> MangaNormAntesMax { get; set; }
        public Nullable<double> ThompsonGapMin { get; set; }
        public Nullable<double> ThompsonGapMax { get; set; }
        public Nullable<double> ThompClampMin { get; set; }
        public Nullable<double> ThompClampMax { get; set; }
        public Nullable<double> ThompBackUpMin { get; set; }
        public Nullable<double> ThompBackUpMax { get; set; }
        public Nullable<double> ThompPlatoMin { get; set; }
        public Nullable<double> ThompPlatoMax { get; set; }
        public Nullable<double> VulcanFrontCollarMin { get; set; }
        public Nullable<double> VulcanFrontCollarMax { get; set; }
        public Nullable<double> VulcanBackCollarMin { get; set; }
        public Nullable<double> VulcanBackCollarMax { get; set; }
        public Nullable<double> VulcanPlungerMin { get; set; }
        public Nullable<double> VulcanPlungerMax { get; set; }
        public Nullable<double> LapRubberSleeveMin { get; set; }
        public Nullable<double> LapRubberSleeveMax { get; set; }
        public Nullable<double> ScotchMangaCMin { get; set; }
        public Nullable<double> ScotchMangaCMax { get; set; }
        public Nullable<double> ScotchMangaDMin { get; set; }
        public Nullable<double> ScotchMangaDMax { get; set; }
        public Nullable<double> ScotchMangaFMin { get; set; }
        public Nullable<double> ScotchMangaFMax { get; set; }
        public Nullable<double> ScotchMangaAMin { get; set; }
        public Nullable<double> ScotchMangaAMax { get; set; }
        public Nullable<double> ScotchMangaBMin { get; set; }
        public Nullable<double> ScotchMangaBMax { get; set; }
        public Nullable<double> BarrelBushingD1Min { get; set; }
        public Nullable<double> BarrelBushingD1Max { get; set; }
        public Nullable<double> BarrelPusherD1Min { get; set; }
        public Nullable<double> BarrelPusherD1Max { get; set; }
        public Nullable<double> NitruLayerMin { get; set; }
        public Nullable<double> NitruLayerMax { get; set; }
        public Nullable<double> AnilloPatronMin { get; set; }
        public Nullable<double> AnilloPatronMax { get; set; }
        public Nullable<double> CromoIntCollarMin { get; set; }
        public Nullable<double> CromoIntCollarMax { get; set; }
    }
}
