//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuffs
    {
        public string no_cuff { get; set; }
        public Nullable<double> dia_ext { get; set; }
        public Nullable<double> dia_int { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> peso { get; set; }
    }
}
