//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuffs
    {
        public string no_cuff { get; set; }
        public Nullable<double> dia_ext { get; set; }
        public Nullable<double> dia_int { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> peso { get; set; }
    }
}
