//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorContraccionLB
    {
        public string Material { get; set; }
        public Nullable<double> fDiametroExtMayorB { get; set; }
        public Nullable<double> fDiametroExtMenor { get; set; }
        public Nullable<double> fWidth { get; set; }
        public Nullable<double> fThickness { get; set; }
    
        public virtual material material1 { get; set; }
    }
}
