//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public string id { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> Recomendado { get; set; }
    
        public virtual Esp_MP_Anillos Esp_MP_Anillos { get; set; }
    }
}
