//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.CAT_MATERIA_PRIMA_ACEROS = new HashSet<CAT_MATERIA_PRIMA_ACEROS>();
            this.CAT_MATERIA_PRIMA_ROLADO = new HashSet<CAT_MATERIA_PRIMA_ROLADO>();
            this.Compensacion_Piece = new HashSet<Compensacion_Piece>();
        }
    
        public string id { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> Recomendado { get; set; }
    
        public virtual FactorContraccion FactorContraccion { get; set; }
        public virtual FactorContraccionLB FactorContraccionLB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_MATERIA_PRIMA_ACEROS> CAT_MATERIA_PRIMA_ACEROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_MATERIA_PRIMA_ROLADO> CAT_MATERIA_PRIMA_ROLADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compensacion_Piece> Compensacion_Piece { get; set; }
        public virtual Esp_MP_Anillos Esp_MP_Anillos { get; set; }
    }
}
