//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.Compensacion_Piece = new HashSet<Compensacion_Piece>();
            this.CAT_MATERIA_PRIMA_ROLADO = new HashSet<CAT_MATERIA_PRIMA_ROLADO>();
        }
    
        public string id { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> Recomendado { get; set; }
    
        public virtual Esp_MP_Anillos Esp_MP_Anillos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compensacion_Piece> Compensacion_Piece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_MATERIA_PRIMA_ROLADO> CAT_MATERIA_PRIMA_ROLADO { get; set; }
    }
}
