//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoutingDia
    {
        public int Id_MountingDia { get; set; }
        public Nullable<double> Plato { get; set; }
        public Nullable<double> Dia_B_min { get; set; }
        public Nullable<double> Dia_B_max { get; set; }
        public Nullable<int> No_impresiones { get; set; }
        public string Gate { get; set; }
        public string Medios_Circulos { get; set; }
        public string Boton { get; set; }
        public string Conos { get; set; }
        public Nullable<int> ord { get; set; }
    }
}
