//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoutingWidth
    {
        public int Id_MountingWidth { get; set; }
        public Nullable<double> Width_Min { get; set; }
        public Nullable<double> Width_Max { get; set; }
        public string Detalle { get; set; }
        public Nullable<double> Altura_Gate { get; set; }
    }
}
