//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoutingWidth
    {
        public int Id_MountingWidth { get; set; }
        public Nullable<double> Width_Min { get; set; }
        public Nullable<double> Width_Max { get; set; }
        public string Detalle { get; set; }
        public Nullable<double> Altura_Gate { get; set; }
    }
}
