//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoutingDia
    {
        public int Id_MountingDia { get; set; }
        public Nullable<double> Plato { get; set; }
        public Nullable<double> Dia_B_min { get; set; }
        public Nullable<double> Dia_B_max { get; set; }
        public Nullable<int> No_impresiones { get; set; }
        public string Gate { get; set; }
        public string Medios_Circulos { get; set; }
        public string Boton { get; set; }
        public string Conos { get; set; }
        public Nullable<int> ord { get; set; }
    }
}
