//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pattern2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pattern2()
        {
            this.patt_actualizaciones = new HashSet<patt_actualizaciones>();
        }
    
        public string codigo { get; set; }
        public Nullable<double> MEDIDA { get; set; }
        public Nullable<double> DIAMETRO { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public string MOUNTING { get; set; }
        public string ON_14_RD_GATE { get; set; }
        public string BUTTON { get; set; }
        public string CONE { get; set; }
        public string M_CIRCLE { get; set; }
        public Nullable<double> RING_WTH_min { get; set; }
        public Nullable<double> RING_WTH_max { get; set; }
        public string DATE_ORDERED { get; set; }
        public Nullable<double> B_DIA { get; set; }
        public Nullable<double> FIN_DIA { get; set; }
        public Nullable<double> TURN_ALLOW { get; set; }
        public Nullable<double> CSTG_SM_OD { get; set; }
        public Nullable<double> SHRINK_ALLOW { get; set; }
        public Nullable<double> PATT_SM_OD { get; set; }
        public Nullable<double> PIECE_IN_PATT { get; set; }
        public Nullable<double> BORE_ALLOW { get; set; }
        public Nullable<double> PATT_SM_ID { get; set; }
        public Nullable<double> PATT_THICKNESS { get; set; }
        public string JOINT { get; set; }
        public string NICK { get; set; }
        public string NICK_DRAF { get; set; }
        public string NICK_DEPTH { get; set; }
        public string SIDE_RELIEF { get; set; }
        public Nullable<double> CAM { get; set; }
        public Nullable<double> CAM_ROLL { get; set; }
        public Nullable<double> RISE { get; set; }
        public Nullable<double> OD { get; set; }
        public Nullable<double> ID { get; set; }
        public Nullable<double> DIFF { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string mounted { get; set; }
        public string ordered { get; set; }
        public string @checked { get; set; }
        public string date_checked { get; set; }
        public string esp_inst { get; set; }
        public Nullable<double> factor_k { get; set; }
        public Nullable<double> rise_built { get; set; }
        public Nullable<double> ring_th_min { get; set; }
        public Nullable<double> ring_th_max { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<double> Plato { get; set; }
        public string Detalle { get; set; }
        public Nullable<bool> Diseno { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patt_actualizaciones> patt_actualizaciones { get; set; }
        public virtual Tipo_Materia_Prima Tipo_Materia_Prima { get; set; }
    }
}
