//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class patt_actualizaciones
    {
        public string codigo_patt { get; set; }
        public string consec_fabr { get; set; }
        public string fecha { get; set; }
        public string nivel { get; set; }
        public string actualizaciones { get; set; }
        public string observaciones { get; set; }
        public int id_patt_actualizaciones { get; set; }
    
        public virtual Pattern2 Pattern2 { get; set; }
    }
}
