//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TubosCL
    {
        public string Tubo { get; set; }
        public Nullable<double> DiaExt { get; set; }
        public Nullable<double> DiaInt { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Largo { get; set; }
    }
}
