//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.MateriasPrimas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TubosHD
    {
        public string Tubo { get; set; }
        public Nullable<double> DiaExt { get; set; }
        public Nullable<double> DiaInt { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Largo { get; set; }
        public string Molde { get; set; }
        public Nullable<int> RPM { get; set; }
    }
}
