//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_MESA_PVD_WASH
    {
        public int ID_MESA_PVD_WASH { get; set; }
        public string NO_MESA { get; set; }
        public Nullable<double> MIN_TECH_AVAILABLE { get; set; }
        public Nullable<double> MAX_TECH_AVAILABLE { get; set; }
        public Nullable<double> MIN_IDEAL_AVAILABLE { get; set; }
        public Nullable<double> MAX_IDEAL_AVAILABLE { get; set; }
    }
}
