//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollarBK
    {
        public int ID_COLLAR_BK { get; set; }
        public string Codigo { get; set; }
        public string Plano { get; set; }
        public string Parte { get; set; }
        public Nullable<double> DimA { get; set; }
        public string DimA_Unidad { get; set; }
        public Nullable<double> DimB { get; set; }
        public string DimB_Unidad { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
