//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriDiaGuillBK
    {
        public int Id_CriDiaGuillBK { get; set; }
        public Nullable<double> RangoMin { get; set; }
        public Nullable<double> RangoMax { get; set; }
        public string Dia { get; set; }
        public string SobreMedida { get; set; }
    }
}
