//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriGillBK
    {
        public int Id_CriGillBK { get; set; }
        public Nullable<double> RangoMin { get; set; }
        public Nullable<double> RangoMax { get; set; }
        public Nullable<double> A { get; set; }
        public string D { get; set; }
        public Nullable<double> E { get; set; }
        public Nullable<double> RangoDiaMin { get; set; }
        public Nullable<double> RangoDiaMax { get; set; }
        public int ident { get; set; }
    }
}
