//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriGPBK
    {
        public int Id_CriGPBK { get; set; }
        public string Width { get; set; }
        public Nullable<double> A { get; set; }
        public int ident { get; set; }
        public int Id_CriGPBK1 { get; set; }
    }
}
