//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriosAnillos
    {
        public int ID_CRITERIO { get; set; }
        public Nullable<double> SpacerMin { get; set; }
        public Nullable<double> SpacerMax { get; set; }
        public Nullable<double> FGGuideBar { get; set; }
        public Nullable<double> CTAnilloPatronMin { get; set; }
        public Nullable<double> CTAnilloPatronMax { get; set; }
        public Nullable<double> CTCollarDimEMin { get; set; }
        public Nullable<double> CTCollarDimEMax { get; set; }
        public Nullable<double> CTCollarDimFMin { get; set; }
        public Nullable<double> CTCollarDimFMax { get; set; }
        public Nullable<double> BoreBushingMin { get; set; }
        public Nullable<double> BoreBushingMax { get; set; }
        public Nullable<double> FinMillBushignMin { get; set; }
        public Nullable<double> FinMillBushignMax { get; set; }
        public Nullable<double> AFTSleeveMin { get; set; }
        public Nullable<double> AFTSleeveMax { get; set; }
        public Nullable<double> Diskus1Min { get; set; }
        public Nullable<double> Diskus1Max { get; set; }
        public Nullable<double> Diskus2Min { get; set; }
        public Nullable<double> Diskus2Max { get; set; }
        public Nullable<double> CriterioDiskus { get; set; }
        public Nullable<double> CriterioSIM { get; set; }
        public Nullable<double> SIMBushingMin { get; set; }
        public Nullable<double> SIMBushingMax { get; set; }
        public Nullable<double> SIMPusherMin { get; set; }
        public Nullable<double> SIMPusherMax { get; set; }
        public Nullable<double> DiaFrank { get; set; }
        public Nullable<double> LapBarrelMin { get; set; }
        public Nullable<double> LapBarrelMax { get; set; }
        public Nullable<double> AFTBarmMax { get; set; }
        public Nullable<double> AFTBarmMin { get; set; }
        public Nullable<double> ScotchbriteCollarMin { get; set; }
        public Nullable<double> ScotchbriteCollarMax { get; set; }
        public Nullable<double> CromoBushingMin { get; set; }
        public Nullable<double> CromoBushingMax { get; set; }
        public Nullable<double> CromoCollarMin { get; set; }
        public Nullable<double> CromoCollarMax { get; set; }
        public Nullable<double> MolyCamisaMin { get; set; }
        public Nullable<double> MolyCamisaMax { get; set; }
        public Nullable<double> MolyCollarMin { get; set; }
        public Nullable<double> MolyCollarMax { get; set; }
        public Nullable<double> MolyProteSupMin { get; set; }
        public Nullable<double> MolyProteSupMax { get; set; }
    }
}
