//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillEngrave_
    {
        public int ID_DRILL_ENGRAVE { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string DIMENCION { get; set; }
        public string DETALLE { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
