//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroHerramentales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroHerramentales()
        {
            this.CollarBK = new HashSet<CollarBK>();
            this.GuideBarFirstRoughGrind = new HashSet<GuideBarFirstRoughGrind>();
            this.GuideBarSecondRoughGrind = new HashSet<GuideBarSecondRoughGrind>();
            this.CutterSpacerSplitter = new HashSet<CutterSpacerSplitter>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string FechaCreacion { get; set; }
        public string FechaCambio { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioCambio { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> idClasificacionHerramental { get; set; }
        public Nullable<int> idPlano { get; set; }
    
        public virtual ClasificacionHerramental ClasificacionHerramental { get; set; }
        public virtual PLANO_HERRAMENTAL PLANO_HERRAMENTAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollarBK> CollarBK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuideBarFirstRoughGrind> GuideBarFirstRoughGrind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuideBarSecondRoughGrind> GuideBarSecondRoughGrind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CutterSpacerSplitter> CutterSpacerSplitter { get; set; }
    }
}
