//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesTooling : DbContext
    {
        public EntitiesTooling()
            : base("name=EntitiesTooling")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClasificacionHerramental> ClasificacionHerramental { get; set; }
        public virtual DbSet<MaestroHerramentales> MaestroHerramentales { get; set; }
        public virtual DbSet<PLANO_HERRAMENTAL> PLANO_HERRAMENTAL { get; set; }
        public virtual DbSet<CollarBK> CollarBK { get; set; }
    }
}
