//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesTooling : DbContext
    {
        public EntitiesTooling()
            : base("name=EntitiesTooling")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClasificacionHerramental> ClasificacionHerramental { get; set; }
        public virtual DbSet<MaestroHerramentales> MaestroHerramentales { get; set; }
        public virtual DbSet<PLANO_HERRAMENTAL> PLANO_HERRAMENTAL { get; set; }
        public virtual DbSet<CollarBK> CollarBK { get; set; }
        public virtual DbSet<CriteriosAnillos> CriteriosAnillos { get; set; }
        public virtual DbSet<GuideBarFirstRoughGrind> GuideBarFirstRoughGrind { get; set; }
        public virtual DbSet<GuideBarSecondRoughGrind> GuideBarSecondRoughGrind { get; set; }
        public virtual DbSet<CutterSpacerSplitter> CutterSpacerSplitter { get; set; }
        public virtual DbSet<TBL_EXTERNAL_GUIDE_ROLLER_1PIECE> TBL_EXTERNAL_GUIDE_ROLLER_1PIECE { get; set; }
        public virtual DbSet<TBL_COIL_CENTER_GUIDE> TBL_COIL_CENTER_GUIDE { get; set; }
        public virtual DbSet<TBL_COIL_FEED_ROLLER> TBL_COIL_FEED_ROLLER { get; set; }
        public virtual DbSet<TBL_EXIT_GUIDE> TBL_EXIT_GUIDE { get; set; }
        public virtual DbSet<TBL_EXTERNAL_GUIDE_ROLLER_3PIECES_1> TBL_EXTERNAL_GUIDE_ROLLER_3PIECES_1 { get; set; }
        public virtual DbSet<TBL_EXTERNAL_GUIDE_ROLLER_3PIECES_2> TBL_EXTERNAL_GUIDE_ROLLER_3PIECES_2 { get; set; }
        public virtual DbSet<TBL_EXTERNAL_GUIDE_ROLLER_3PIECES_3> TBL_EXTERNAL_GUIDE_ROLLER_3PIECES_3 { get; set; }
        public virtual DbSet<TBL_SHIM_OF_THE_CUT_SYSTEM> TBL_SHIM_OF_THE_CUT_SYSTEM { get; set; }
        public virtual DbSet<SplitterSpacerChart> SplitterSpacerChart { get; set; }
        public virtual DbSet<SPlitterSpacerChart2> SPlitterSpacerChart2 { get; set; }
        public virtual DbSet<ChuckSplitter> ChuckSplitter { get; set; }
        public virtual DbSet<CutterSplitter> CutterSplitter { get; set; }
        public virtual DbSet<UretanoSplitter> UretanoSplitter { get; set; }
    }
}
