//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShieldBK_
    {
        public int Id_ShieldBK { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> FractionalMin { get; set; }
        public Nullable<double> FractionalMax { get; set; }
        public string Detalle { get; set; }
        public string FracMin { get; set; }
        public string FracMax { get; set; }
        public int Id_ShieldBK1 { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
