//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class SplitterSpacerChart
    {
        public Nullable<double> Nominal_split { get; set; }
        public Nullable<double> Jaw_Block_Length { get; set; }
        public Nullable<double> Jaw_Block_min { get; set; }
        public Nullable<double> Jaw_Block_max { get; set; }
        public Nullable<double> Thrust_shoe_width { get; set; }
        public Nullable<double> Cutter_spacer { get; set; }
        public Nullable<double> Castings_per_chuck { get; set; }
        public Nullable<double> Split_width { get; set; }
        public Nullable<double> Split_min { get; set; }
        public Nullable<double> Split_max { get; set; }
        public Nullable<double> Grind_width { get; set; }
        public string Proceso { get; set; }
        public int ident { get; set; }
    }
}
