//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BARREL_GRADE_BUSHING
    {
        public int ID_BARREL_GRADE_BUSHING { get; set; }
        public string CODIGO { get; set; }
        public Nullable<double> DIM_D { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
