//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FEED_WHEEL_RECTIFICADOS_FINOS
    {
        public int ID_FEED_WHEEL_RECTIFICADOS_FINOS { get; set; }
        public string CODIGO { get; set; }
        public Nullable<double> DIM_DIAMETRO { get; set; }
        public Nullable<double> DIM_WIDTH { get; set; }
        public Nullable<double> DIM_F { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
