//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONF_DIMA_COLLAR_LAPEADO_SEGMENTOS
    {
        public int ID_CONF_COLLAR_LAPEADO_SEGMENTOS { get; set; }
        public Nullable<double> DIAMETRO_MIN { get; set; }
        public Nullable<double> DIAMETRO_MAX { get; set; }
        public Nullable<double> THICKNESS_UP_100 { get; set; }
        public Nullable<double> THICKNESS_DOWN_100 { get; set; }
    }
}
