//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONF_PLUS_COLLAR_LAPEADO_SEGMENTOS
    {
        public int ID_CONF_PLUS_COLLAR_LAPEADO_SEGMENTOS { get; set; }
        public Nullable<double> MINIMO { get; set; }
        public Nullable<double> MAXIMO { get; set; }
        public string DETALLE { get; set; }
    }
}
