//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MANGA_PVD_ACERO_INOXIDABLE
    {
        public int ID_MANGA_PVD_ACERO_INOXIDABLE { get; set; }
        public double N_MIN { get; set; }
        public double N_MAX { get; set; }
        public double A { get; set; }
        public Nullable<double> FACTOR { get; set; }
    }
}
