//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOBINADO_CENTER_WAFER
    {
        public int ID_BOBONADO_CENTER_WAFER { get; set; }
        public string CODIGO { get; set; }
        public Nullable<double> DIM_A_MIN { get; set; }
        public Nullable<double> DIM_A_MAX { get; set; }
        public Nullable<double> WIRE_WIDTH { get; set; }
        public string DETALLE { get; set; }
        public Nullable<double> DIA_B { get; set; }
        public Nullable<double> F_WIDTH { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
