//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PLATO_EMPUJADOR_THOMPSON_SEGMENTOS
    {
        public int ID_PLATO_EMPUJADOR { get; set; }
        public string CODIGO { get; set; }
        public double DIM_A { get; set; }
        public string PARTE { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
