//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Tooling
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCam
    {
        public int Id_WorkCam { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string MedidaNominal { get; set; }
        public int ident { get; set; }
        public int Id_WorkCam1 { get; set; }
    
        public virtual MaestroHerramentales MaestroHerramentales { get; set; }
    }
}
