//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPO_PERFIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TIPO_PERFIL()
        {
            this.CAT_PERFIL = new HashSet<CAT_PERFIL>();
        }
    
        public int ID_TIPO_PERFIL { get; set; }
        public string PERFIL { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<int> ID_USUARIO_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PERFIL> CAT_PERFIL { get; set; }
    }
}
