//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PERFIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_PERFIL()
        {
            this.TR_PERFIL_ARQUETIPO = new HashSet<TR_PERFIL_ARQUETIPO>();
            this.TR_PROPIEDAD_BOOL_PERFIL = new HashSet<TR_PROPIEDAD_BOOL_PERFIL>();
            this.TR_PROPIEDAD_CADENA_PERFIL = new HashSet<TR_PROPIEDAD_CADENA_PERFIL>();
            this.TR_PROPIEDAD_PERFIL = new HashSet<TR_PROPIEDAD_PERFIL>();
            this.TR_PROPIEDAD_OPCIONAL_PERFIL = new HashSet<TR_PROPIEDAD_OPCIONAL_PERFIL>();
        }
    
        public int ID_PERFIL { get; set; }
        public int ID_TIPO_PERFIL { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] IMAGEN { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<int> ID_USUARIO_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
    
        public virtual CAT_TIPO_PERFIL CAT_TIPO_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_PERFIL_ARQUETIPO> TR_PERFIL_ARQUETIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_PROPIEDAD_BOOL_PERFIL> TR_PROPIEDAD_BOOL_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_PROPIEDAD_CADENA_PERFIL> TR_PROPIEDAD_CADENA_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_PROPIEDAD_PERFIL> TR_PROPIEDAD_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_PROPIEDAD_OPCIONAL_PERFIL> TR_PROPIEDAD_OPCIONAL_PERFIL { get; set; }
    }
}
