//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_OPCION_PROPIEDAD_OPCIONAL
    {
        public int ID_OPCION_PROPIEDAD_OPCIONAL { get; set; }
        public Nullable<int> ID_PROPIEDAD_OPCIONAL { get; set; }
        public string VALOR { get; set; }
    
        public virtual CAT_PROPIEDAD_OPCIONAL CAT_PROPIEDAD_OPCIONAL { get; set; }
    }
}
