//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesPerfiles : DbContext
    {
        public EntitiesPerfiles()
            : base("name=EntitiesPerfiles")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_PERFIL> CAT_PERFIL { get; set; }
        public virtual DbSet<CAT_PROPIEDAD> CAT_PROPIEDAD { get; set; }
        public virtual DbSet<CAT_PROPIEDAD_BOOL> CAT_PROPIEDAD_BOOL { get; set; }
        public virtual DbSet<CAT_PROPIEDAD_CADENA> CAT_PROPIEDAD_CADENA { get; set; }
        public virtual DbSet<CAT_TIPO_PERFIL> CAT_TIPO_PERFIL { get; set; }
        public virtual DbSet<TR_PROPIEDAD_BOOL_PERFIL> TR_PROPIEDAD_BOOL_PERFIL { get; set; }
        public virtual DbSet<TR_PROPIEDAD_CADENA_PERFIL> TR_PROPIEDAD_CADENA_PERFIL { get; set; }
        public virtual DbSet<TR_PROPIEDAD_PERFIL> TR_PROPIEDAD_PERFIL { get; set; }
    }
}
