//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESPEC_PVD_RAILS
    {
        public int ID_ESPEC_PVD_RAILS { get; set; }
        public string ESPECIFICACION_PVD { get; set; }
        public Nullable<double> THICKNESS_MIN { get; set; }
        public Nullable<double> THICKNESS_MAX { get; set; }
        public Nullable<double> DUREZA_MIN { get; set; }
        public Nullable<double> DUREZA_MAX { get; set; }
        public string NO_RECETA { get; set; }
    }
}
