//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESPEC_PVD_RAILS
    {
        public int ID_ESPEC_PVD_RAILS { get; set; }
        public string ESPECIFICACION_PVD { get; set; }
        public Nullable<double> THICKNESS_MIN { get; set; }
        public Nullable<double> THICKNESS_MAX { get; set; }
        public Nullable<double> DUREZA_MIN { get; set; }
        public Nullable<double> DUREZA_MAX { get; set; }
        public string NO_RECETA { get; set; }
    }
}
