//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROLLOS_CAJA_SEGMENTOS
    {
        public int ID_ROLLOS_CAJA_SEGMENTOS { get; set; }
        public Nullable<int> ID_NO_CAJA { get; set; }
        public Nullable<double> DIAMETRO_MIN { get; set; }
        public Nullable<double> DIAMETRO_MAX { get; set; }
        public Nullable<int> ROLLOS_CAJA { get; set; }
    
        public virtual TBL_NO_CAJA TBL_NO_CAJA { get; set; }
    }
}
