//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NORMAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_NORMAS()
        {
            this.TR_NORMAS_ARQUETIPO = new HashSet<TR_NORMAS_ARQUETIPO>();
        }
    
        public int ID_NORMA { get; set; }
        public string ESPECIFICACION { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_NORMAS_ARQUETIPO> TR_NORMAS_ARQUETIPO { get; set; }
    }
}
