//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARQUETIPO_PROPIEDADES
    {
        public int ID_ARQUETIPO_PROPIEDADES { get; set; }
        public string CODIGO { get; set; }
        public int ID_PROPIEDAD { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<double> VALOR { get; set; }
    
        public virtual Arquetipo Arquetipo { get; set; }
        public virtual CAT_PROPIEDAD CAT_PROPIEDAD { get; set; }
    }
}
