//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PZA_ROLLO_SEGMENTO
    {
        public int ID_PZA_ROLLO_SEGMENTO { get; set; }
        public Nullable<double> WIDTH_SEGMENTO { get; set; }
        public Nullable<int> PIEZAS { get; set; }
    }
}
