//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NORMAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_NORMAS()
        {
            this.TR_NORMAS_ARQUETIPO = new HashSet<TR_NORMAS_ARQUETIPO>();
        }
    
        public int ID_NORMA { get; set; }
        public string ESPECIFICACION { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string DESCRIPCION_LARGA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_NORMAS_ARQUETIPO> TR_NORMAS_ARQUETIPO { get; set; }
    }
}
