//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PZA_ROLLO_SEGMENTO
    {
        public int ID_PZA_ROLLO_SEGMENTO { get; set; }
        public Nullable<double> WIDTH_SEGMENTO { get; set; }
        public Nullable<int> PIEZAS { get; set; }
    }
}
