//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARQUETIPO_PROPIEDADES_BOOL
    {
        public int ID_ARQUETIPO_PROPIEDADES_BOOL { get; set; }
        public string CODIGO { get; set; }
        public int ID_PROPIEDAD_BOOL { get; set; }
        public Nullable<bool> VALOR { get; set; }
    
        public virtual Arquetipo Arquetipo { get; set; }
        public virtual CAT_PROPIEDAD_BOOL CAT_PROPIEDAD_BOOL { get; set; }
    }
}
