//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Perfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PERFIL_ARQUETIPO
    {
        public int ID_PERFIL_ARQUETIPO { get; set; }
        public string CODIGO { get; set; }
        public int ID_PERFIL { get; set; }
    
        public virtual Arquetipo Arquetipo { get; set; }
        public virtual CAT_PERFIL CAT_PERFIL { get; set; }
    }
}
