//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DOCUMENTO_FIRMADO
    {
        public int ID_DOCUMENTO_FIRMADO { get; set; }
        public Nullable<int> ID_VERSION { get; set; }
        public string PATH_DOCUMENTO { get; set; }
        public byte[] ARCHIVO { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public string EXT { get; set; }
    
        public virtual TBL_VERSION TBL_VERSION { get; set; }
    }
}
