//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SOLICITUD_CONTROL_DOCUMENTO
    {
        public int ID_SOLICITUD_CONTROL_DOCUMENTO { get; set; }
        public int ID_VERSION { get; set; }
        public string ACCION { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public Nullable<bool> BAN_EJECUTADA { get; set; }
        public Nullable<System.DateTime> FECHA_EJECUCION { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual TBL_VERSION TBL_VERSION { get; set; }
    }
}
