//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INFORMACION_FRAMES
    {
        public int ID_INFORMACION_FRAMES { get; set; }
        public string NOMBRE_DOCUMENTO { get; set; }
        public string VERSION { get; set; }
        public Nullable<System.DateTime> FECHA_LIBERACION { get; set; }
    }
}
