//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DOCUMENTO_ELIMINADO
    {
        public int ID_ELIMINADO { get; set; }
        public string NUM_DOCUMENTO { get; set; }
        public string NO_VERSION { get; set; }
        public byte[] ARCHIVO { get; set; }
        public string EXT { get; set; }
        public System.DateTime FECHA_ELIMINO { get; set; }
    }
}
