//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;

    public partial class TBL_ARCHIVO
    {
        public int ID_ARCHIVO { get; set; }
        public Nullable<int> ID_VERSION { get; set; }
        public byte[] ARCHIVO { get; set; }
        public string EXT { get; set; }
    
        public virtual TBL_VERSION TBL_VERSION { get; set; }
    }
}
