//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONF_DOCUMENTO
    {
        public int ID_CONF_DOCUMENTO { get; set; }
        public int ID_TIPO_DOCUMENTO { get; set; }
        public Nullable<int> PERIODO_ANIOS_ACTUALIZACION { get; set; }
    
        public virtual TBL_TIPO_DOCUMENTO TBL_TIPO_DOCUMENTO { get; set; }
    }
}
