//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GRUPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_GRUPOS()
        {
            this.TR_INTEGRANTES_GRUPO = new HashSet<TR_INTEGRANTES_GRUPO>();
            this.TR_GRUPO_VERSION = new HashSet<TR_GRUPO_VERSION>();
        }
    
        public int ID_GRUPO { get; set; }
        public string NOMBRE { get; set; }
        public string ID_USUARIO_DUENO { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_INTEGRANTES_GRUPO> TR_INTEGRANTES_GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_GRUPO_VERSION> TR_GRUPO_VERSION { get; set; }
    }
}
