//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.ControlDocumentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.TBL_DOCUMENTO = new HashSet<TBL_DOCUMENTO>();
            this.TR_ROL_USUARIOS = new HashSet<TR_ROL_USUARIOS>();
            this.TBL_VERSION = new HashSet<TBL_VERSION>();
            this.TBL_VERSION1 = new HashSet<TBL_VERSION>();
            this.TBL_GRUPOS = new HashSet<TBL_GRUPOS>();
            this.TR_INTEGRANTES_GRUPO = new HashSet<TR_INTEGRANTES_GRUPO>();
        }
    
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string APaterno { get; set; }
        public string AMaterno { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Usql { get; set; }
        public string Psql { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public string Correo { get; set; }
        public string Pathnsf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DOCUMENTO> TBL_DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_ROL_USUARIOS> TR_ROL_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_VERSION> TBL_VERSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_VERSION> TBL_VERSION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_GRUPOS> TBL_GRUPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_INTEGRANTES_GRUPO> TR_INTEGRANTES_GRUPO { get; set; }
    }
}
