//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Operaciones.Premaquinado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesPreMaquinado : DbContext
    {
        public EntitiesPreMaquinado()
            : base("name=EntitiesPreMaquinado")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SPlitterSpacerChart2> SPlitterSpacerChart2 { get; set; }
        public virtual DbSet<SplitterSpacerChart> SplitterSpacerChart { get; set; }
    }
}
