//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Operaciones.Premaquinado
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPlitterSpacerChart2
    {
        public string Proceso { get; set; }
        public Nullable<double> RingWidth { get; set; }
        public Nullable<double> SplitWidth { get; set; }
        public Nullable<double> GrindWidth { get; set; }
        public Nullable<double> CutterSpacer1 { get; set; }
        public Nullable<double> CantidadSpacer1 { get; set; }
        public Nullable<double> CutterSpacer2 { get; set; }
        public Nullable<double> CantidadSpacer2 { get; set; }
        public int ident { get; set; }
    }
}
