//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ServiceObjects.Notificaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOTIFICACIONES
    {
        public int ID_NOTIFICACION { get; set; }
        public string ID_USUARIO_SEND { get; set; }
        public string ID_USUARIO_RECEIVER { get; set; }
        public string TITLE { get; set; }
        public string MSG { get; set; }
        public Nullable<int> TYPE_NOTIFICATION { get; set; }
    }
}
